flowchart LR
EUC[EraRule UTXOW Conway]
    EUC --> babbageUtxowTransition
        babbageUtxowTransition --> validateFailedBabbageScripts(validateFailedBabbageScripts)
        babbageUtxowTransition --> babbageMissingScripts(babbageMissingScripts)
        babbageUtxowTransition --> missingRequiredDatums(missingRequiredDatums)
        babbageUtxowTransition --> hasExactSetOfRedeemers(hasExactSetOfRedeemers)
        babbageUtxowTransition --> validateVerifiedWits(Shelley.validateVerifiedWits)
        babbageUtxowTransition --> validateNeededWitnesses(validateNeededWitnesses)
        babbageUtxowTransition --> validateMetdata(Shelley.validateMetadata)
        babbageUtxowTransition --> validateScriptsWellFormed(validateScriptsWellFormed)
        babbageUtxowTransition --> ppViewHashesMatch(ppViewHashesMatch)
        babbageUtxowTransition --> EUTXOC[EraRule UTXO Conway]
            EUTXOC --> utxoTransition
                utxoTransition --> disjointRefInputs(disjointRefInputs)
                utxoTransition --> validateOutsideValidityIntervalUtxo(Allegra.validateOutsideValidityIntervalUtxo)
                utxoTransition --> validateOutsideForecast(Alonzo.validateOutsideForecast)
                utxoTransition --> validateInputSetEmptyUTxO(Shelley.validateInputSetEmptyUTxO)
                utxoTransition --> feesOk(feesOk)
                utxoTransition --> validateBadInputsUTxO(Shelley.validateBadInputsUTxO)
                utxoTransition --> validateValueNotConservedUTxO(Shelley.validateValueNotConservedUTxO)
                utxoTransition --> validateOutputTooSmallUTxO(validateOutputTooSmallUTxO)
                utxoTransition --> validateOutputTooBigUTxO(Alonzo.validateOutputTooBigUTxO)
                utxoTransition --> validateOutputBootAddrAttrsTooBig(Shelley.validateOuputBootAddrAttrsTooBig)
                utxoTransition --> validateWrongNetwork(Shelley.validateWrongNetwork)
                utxoTransition --> validateWrongNetworkWithdrawal(Shelley.validateWrongNetworkWithdrawal)
                utxoTransition --> validateWrongNetworkInTxBody(Alonzo.validateWrongNetworkInTxBody)
                utxoTransition --> validateMaxTxSizeUTxO(Shelley.vallidateMaxTxSizeUTxO)
                utxoTransition --> validateExUnitsTooBigUTxO(Alonzo.validateExUnitsTooBigUTxO)
                utxoTransition --> EUTXOSC[EraRule UTXOS Conway]
                    EUTXOSC --> utxosTransition
                utxosTransition --> isValidTxL{isValidTxL}
                    isValidTxL --> |True| conwayEvalScriptsTxValid
                        conwayEvalScriptsTxValid --> expectScriptsToPass(expactScriptsToPass)
                        conwayEvalScriptsTxValid --> conwayEvalScriptsTxValidUtxosPrime[(utxos')]
                    isValidTxL --> |False| babbageEvalScriptsTxInvalid
                        babbageEvalScriptsTxInvalid --> evalPlutusScripts(evalPlutusScripts FAIL)
                        babbageEvalScriptsTxInvalid --> babbageEvalScriptsTxInvalidUtxosPrime([utxos'])
    EUC --> LedgerState[(LedgerState utxoState'' certStateAfterCERTS)]
