flowchart LR
    ELC[EraRule LEDGERS Conway]
                    ELC --> ELS[EraRule LEDGERS Shelley]
                    ELS --> ledgersTransition
                        ledgersTransition --> |repeat| ledgerTransition
                            ledgerTransition --> |when mempool| EMC[EraRule Mempool Conway]
                                EMC --> mempoolTransition
                                    mempoolTransition --> unelectedCommitteeMembers(failOnNonEmpty unelectedCommitteeMembers)
                            ledgerTransition --> isValid{isValid}
                                isValid --> |True| ltDoBlock[do]
                                    ltDoBlock --> |currentTreasuryValueTxBodyL| submittedTreasuryValue(submittedTreasuryValue == actualTreasuryValue)
                                    ltDoBlock --> totalRefScriptSize(totalRefScriptSize <= maxRefScriptSizePerTx)
                                    ltDoBlock  --> nonExistentDelegations(failOnNonEmpty nonExistentDelegations)

                                    ltDoBlock --> ECSC[EraRule CERTS Conway]
                                    ltDoBlock --> EGC[EraRule GOV Conway]
                                    ltDoBlock --> utxoState[(utxoState', certStateAfterCerts)]
                                isValid --> |False| utxoStateCertState[(utxoState, certState)]
                            ledgerTransition --> EUC[EraRule UTXOW Conway]
