[book]
authors = ["Sebastian Nagel", "Paul Clark"]
description = "Implementation-independent specifications of the Cardano protocol"
language = "en"
src = "src"
title = "Cardano Blueprint"

[build]
build-dir = "out"

[preprocessor.mermaid]
command = "mdbook-mermaid"

[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]

[preprocessor.katex]
after = ["links"]

[output.html]
additional-css = [".mdbook/custom.css"]
additional-js = [".mdbook/mermaid.min.js", ".mdbook/mermaid-init.js"]
smart-punctuation = true
site-url = "/cardano-blueprint/"
git-repository-url = "https://github.com/cardano-scaling/cardano-blueprint/tree/main"
edit-url-template = "https://github.com/cardano-scaling/cardano-blueprint/edit/main/{path}"
