# The formatter multiplexer - https://github.com/numtide/treefmt
[formatter.mdformat]
command = "mdformat"
excludes = []
includes = ["*.md"]
options = ["--extensions", "gfm", "--extensions", "footnote", "--extensions", "myst"]

# TODO: figure out how to exclude certain phrases and disable on code blocks
# [formatter.typos]
# command = "typos"
# excludes = []
# includes = ["*.md"]
# options = ["--write-changes"]
