# The formatter multiplexer - https://github.com/numtide/treefmt
[formatter.mdformat]
command = "mdformat"
excludes = []
includes = ["*.md"]
options = ["--extensions", "gfm", "--extensions", "footnote", "--extensions", "myst"]

[formatter.typos]
command = "typos"
excludes = []
includes = ["*.md"]
options = ["--write-changes"]
