txSubmission2Message
    = msgInit
    ; corresponds to either MsgRequestTxIdsBlocking or
    ; MsgRequestTxIdsNonBlocking in the spec
    / msgRequestTxIds
    / msgReplyTxIds
    / msgRequestTxs
    / msgReplyTxs
    / tsMsgDone


msgInit         = [6]
msgRequestTxIds = [0, tsBlocking, txCount, txCount]
msgReplyTxIds   = [1, txIdsAndSizes ]
msgRequestTxs   = [2, txIdList ]
msgReplyTxs     = [3, txList ]
tsMsgDone       = [4]

tsBlocking      = false / true
txCount         = base.word16
; The codec only accepts indefinite-length lists.
txIdList        = [ *txId.txId ]
txList          = [ *tx.tx ]
txIdAndSize     = [base.txId, txSizeInBytes]
; The codec only accepts definite-length lists.
txIdsAndSizes   = [ *txIdAndSize ]
txSizeInBytes   = base.word32

;# import tx as tx
;# import txId as txId
;# import base as base
