name: Formating and spell-checking

on:
  pull_request:
  push:
    branches:
    - main

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  treefmt:
    name: Formatting and spell-checking
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install nix
        uses: cachix/install-nix-action@V27
        with:
          extra_nix_config: |
            accept-flake-config = true
            log-lines = 1000

      - name: Enter nix shell
        uses: nicknovitski/nix-develop@v1

      - name: Run treefmt
        run: treefmt --ci
